name: Build, Push to ACR, and Deploy to ACI

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dynamic Docker tag
        id: vars
        run: |
          echo "tag=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/etl-csv:${{ steps.vars.outputs.tag }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/etl-csv:${{ steps.vars.outputs.tag }}

      - name: Deploy to Azure Container Instance
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name csv-etl-job \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/etl-csv:${{ steps.vars.outputs.tag }} \
            --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --os-type Linux \
            --cpu 1 \
            --memory 1.5 \
            --environment-variables \
              AZURE_STORAGE_CONNECTION_STRING="${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              LOGIC_APP_URL="${{ secrets.LOGIC_APP_URL }}" \
            --restart-policy Never
